### ISSUE TITLE
[djangoflow_auth] Check ways to integrate Openapi library in djangoflow_auth package

### ISSUE THREAD

**Issue by adar2378** [djangoflow/flutter-djangoflow#35]

**Comment by dorx-code-lab** [comment]
Could you please elaborate on this? What do you mean integrating OpenAPI Library in Djangoflow Auth? Do you mean having OpenAI as an auth option, just like google and facebook login?

**Comment by adar2378** [comment]
Hi @dorx-code-lab , thanks for your interest. This issue is already assigned on me. So please work on other issues that are not assigned on anyone.

**Comment by adar2378** [comment]
Done, via djangoflow_openapi library and overriding it via locally generated djangoflow_openapi library.
