### ISSUE TITLE
[djangoflow_chat] Implement complimentary flutter module for https://github.com/djangoflow/django-df-chat

### ISSUE THREAD

**Issue by adar2378** [djangoflow/flutter-djangoflow#36]
Currently, we have a Django module for chat https://github.com/djangoflow/django-df-chat

Need to implement Flutter part of it which will communicate with the backend and 
- Fetch messages with pagination
- Send text message, image message (in future we could add more types support)
- Mark messages as seen
- Realtime message update via websocket
- Reaction

**Comment by sofiapex** [comment]
@ayushin confirmed this issue is closed
