### ISSUE TITLE
[djangoflow_fcm] After permission is granted getToken throws Subscription failed - no active Service Worker

### ISSUE THREAD

**Issue by adar2378** [djangoflow/flutter-djangoflow#74]
I have done a temporary workaround for now using https://github.com/firebase/flutterfire/issues/11798#issuecomment-1826360250
This is a bug due to firebase_messaging pacakge. It's being tracked here. Will close this ticket once firebase team addresses the issue.
https://github.com/firebase/flutterfire/issues/11954

**Comment by adar2378** [comment]
Fixed on firebase_messaging

**Comment by AbhayJadoun** [comment]
iin which update can you please mention the release version.
